### ISSUE TITLE
Architecture étrange

### ISSUE THREAD

**Issue by Nek-** [Omegadela/Angular#1]
Hello,

Le résultat est tout à fait ce que j'attendais.

Je voulais tout de même faire une parenthèse par rapport à ton architecture: tu as tout placé dans `app.js` au lieu de créer un contrôleur dans le dossier prévu à cet effet ;) .

P.S.: tu peux supprimer ce repository si tu le souhaites maintenant.

**Comment by Omegadela** [comment]
Si je le *refactor* la note change ? :smiley:
